spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能
          enabled: true
          #使用小写服务名，默认是大写
          lower-case-service-id: true
dynamic:
  route:
    address: 10.8.160.110:8848
    dataId: dynamic-route-config
    namespace: 91cb002f-fa4f-4e4d-a0c3-2bad50ee8f9c